name: Build and Release
on:
  push:
    branches:
      - "main"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: gradle:8-jdk17
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'gradle'

      - name: Gradle Build
        run: gradle build

      - name: Release
        uses: GeyserMC/actions/release@master
        with:
          files: |
            build/libs/TransferTool-*.jar
          appID: ${{ secrets.RELEASE_APP_ID }}
          appPrivateKey: ${{ secrets.RELEASE_APP_PK }}
          saveMetadata: true
          releaseEnabled: true
          discordWebhook: ${{ secrets.DISCORD_WEBHOOK }}
          ghReleaseNotes: true
          releaseName: Build ${tagBase}
          tagPrefix: release
          tagIncrement: true
          preRelease: false